path: .
jobs: 10
warning: true
cache-dir: var/.phplint.cache
cache-adapter: Filesystem
cache-ttl: 1296000
log-json: var/.phplint.log.json
extensions:
  - php
exclude:
  - vendor
  - vendor-bin
  - var
