version: "3.7"
services:
  api:
    build:
      context: .docker
      dockerfile: dev/nginx/Dockerfile
    volumes:
      - .:/app
    depends_on:
      - api-php-fpm
    ports:
      - "${APP_EXTERNAL_PORT}:80"
    networks:
      bglapinet:
        ipv4_address: "${APP_NETWORK_IP}"
      default:
        aliases:
          - ${APP_HOST}
    links:
      - db-postgres:db
      - mailer
    extra_hosts:
      - "db:${DB_NETWORK_IP}"
      - "mailer:${MAILER_NETWORK_IP}"
      - "${APP_HOST}:${APP_NETWORK_IP}"
    restart: on-failure
    tty: false

  api-php-fpm:
    build:
      context: .docker
      dockerfile: dev/php-fpm/Dockerfile
    environment:
      APP_ENV: dev
      APP_DEBUG: ${APP_DEBUG}
      PHP_IDE_CONFIG: serverName=API
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      MAILER_DSN: ${MAILER_DSN}
      MAIL_NOREPLY: ${MAIL_NOREPLY}
      FRONTEND_URL: ${FRONTEND_URL}
      MAILER_URL: ${MAILER_URL}
      JWT_KEY: ${JWT_KEY}
      JWT_ALGO: ${JWT_ALGO}
      TWIG_ENABLE_CACHE: ${TWIG_ENABLE_CACHE}
    volumes:
      - .:/app
    networks:
      bglapinet:
        ipv4_address: ${FPM_NETWORK_IP}
        aliases:
          - api-php-fpm
    links:
      - db-postgres:db
      - mailer
    extra_hosts:
      - "db:${DB_NETWORK_IP}"
      - "mailer:${MAILER_NETWORK_IP}"
      - "${APP_HOST}:${APP_NETWORK_IP}"
    expose:
      - 9000

  api-php-cli:
    build:
      context: .docker
      dockerfile: dev/php-cli/Dockerfile
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      MAILER_DSN: ${MAILER_DSN}
      MAIL_NOREPLY: ${MAIL_NOREPLY}
      FRONTEND_URL: ${FRONTEND_URL}
      MAILER_URL: ${MAILER_URL}
      JWT_KEY: ${JWT_KEY}
      JWT_ALGO: ${JWT_ALGO}
      TWIG_ENABLE_CACHE: ${TWIG_ENABLE_CACHE}
    volumes:
      - .:/app
    networks:
      - bglapinet
    links:
      - db-postgres:db
      - mailer
    extra_hosts:
      - "db:${DB_NETWORK_IP}"
      - "mailer:${MAILER_NETWORK_IP}"
      - "${APP_HOST}:${APP_NETWORK_IP}"

  db-postgres:
    image: postgres:16.2-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - api-postgres:/var/lib/postgresql/data
    ports:
      - "${DB_EXTERNAL_PORT}:${DB_PORT}"
    logging:
      driver: json-file
      options:
        max-size: "128m"
        max-file: "10"
    networks:
      bglapinet:
        ipv4_address: "${DB_NETWORK_IP}"
        aliases:
          - db
    extra_hosts:
      - "db:${DB_NETWORK_IP}"
    restart: on-failure

  mailer:
    image: mailhog/mailhog
    ports:
      - "${MAILER_EXTERNAL_PORT}:${MAILER_HTTP_PORT}"
    networks:
      - bglapinet

  api-prod:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      APP_ENV: prod
      APP_DEBUG: false
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      MAILER_DSN: ${MAILER_DSN}
      MAIL_NOREPLY: ${MAIL_NOREPLY}
      FRONTEND_URL: ${FRONTEND_URL}
      MAILER_URL: ${MAILER_URL}
      JWT_KEY: ${JWT_KEY}
      JWT_ALGO: ${JWT_ALGO}
      TWIG_ENABLE_CACHE: ${TWIG_ENABLE_CACHE}
    volumes:
      - .:/app
    ports:
      - "${APP_EXTERNAL_PORT_PROD}:81"
    networks:
      bglapinet:
        ipv4_address: "${APP_NETWORK_IP_PROD}"
      default:
        aliases:
          - ${APP_HOST_PROD}
    extra_hosts:
      - "${APP_HOST_PROD}:${APP_NETWORK_IP_PROD}"
    restart: on-failure
    tty: false
    depends_on:
      - api

volumes:
  api-postgres:

networks:
  bglapinet:
    ipam:
      driver: default
      config:
        - subnet: "${BGLNET}"
