version: "3.7"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      JWT_KEY: ${JWT_KEY}
      JWT_ALGO: ${JWT_ALGO}
    volumes:
      - .:/app
    ports:
      - "8000:80"
