version: "3.7"
services:
  api:
    build:
      context: .docker
      dockerfile: dev/nginx/Dockerfile
    volumes:
      - .:/app
    depends_on:
      - api-php-fpm
    ports:
      - "8000:80"

  api-php-fpm:
    build:
      context: .docker
      dockerfile: dev/php-fpm/Dockerfile
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
      PHP_IDE_CONFIG: serverName=API
    volumes:
      - .:/app

  api-php-cli:
    build:
      context: .docker
      dockerfile: dev/php-cli/Dockerfile
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
    volumes:
      - .:/app

  db-postgres:
    image: postgres:15.2-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - api-postgres:/var/lib/postgresql/data
    ports:
      - "54321:5432"

volumes:
  api-postgres:
