#!/usr/bin/env php
<?php

declare(strict_types=1);

use Doctrine\ORM\Tools\Console\ConsoleRunner;
use Doctrine\ORM\Tools\Console\EntityManagerProvider\SingleManagerProvider;

include __DIR__ . '/../vendor/autoload.php';

/** @var \Psr\Container\ContainerInterface $container */
$container = require __DIR__ . '/../config/container.php';

/** @var list<\Symfony\Component\Console\Command\Command> $migrationCommands */
$migrationCommands = $container->get('migrations:commands');

ConsoleRunner::run($container->get(SingleManagerProvider::class), $migrationCommands);
